name: Integrate Laravel Pint with Github Actions
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

      - name: Check code style
        run: ./vendor/bin/pint --test --preset laravel