name: Linting
on: [push]
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Linting use laravel-pint
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true